### ISSUE TITLE
Inner States of DES: Missing context help and plugin description in the online help.

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#217]

**Comment by simlei** [comment]
This is what the full extent of the online help looks like:
![image](https://user-images.githubusercontent.com/982379/66764211-9482e200-eea9-11e9-8521-4db5cabb99ad.png)

**Comment by be4** [comment]
I don't understand where the problem here ism but maybe I miss something:
- This short text with the reference to a paper is there in both,
English and German onlinehelp.
- The referred PDF is there in German and English and explains both some
theory and how to use the plugin.
- What's different to other plugin's onlinehelps is mainly, that there
are no screemshots in the PDFs.
  However this is nothing necessary for version 1.0
- The author's reason to use a PDF was, that the explanation in this
onlinehelp massively used mathematical formulars.

Best regards, BE



Am 14.10.2019 um 17:39 schrieb Simon Leischnig:
> This is what the full extent of the online help looks like:
> ![image](https://user-images.githubusercontent.com/982379/66764211-9482e200-eea9-11e9-8521-4db5cabb99ad.png)
>
>

**Comment by simlei** [comment]
Alright, I don't have any particular issue with this being the Online help. Glad to have revisited it though. I would not have been sure as I don't see myself exactly a help expert. This does not change that this issue is mainly about  a missing context help.

The context help issue still stands:
![image](https://user-images.githubusercontent.com/982379/66772190-71156280-eebc-11e9-98a3-4933d6cd4518.png)

**Comment by simlei** [comment]
Closing because also the context help issue is about to be fixed by another issue.
