### ISSUE TITLE
Multipartite Key Exchange: Missing online- and context-help in DE and EN

### ISSUE THREAD

**Issue by grthor** [jcryptool/crypto#220]

**Comment by grthor** [comment]
I think @CharlotteMagister is currently working on it. Maybe she can give a shot summary on her current status.

**Comment by CharlotteMagister** [comment]
Hi,

I'm sorry for the late reply. The instructions I had for the plug-in also included changes to the code. I mostly concentrated on that, however, I haven't finished it. I have not started on any translations yet, because I was going to finish the implementation changes first (Issue 230).

Thank you.

**Comment by grthor** [comment]
Hi @CharlotteMagister , thanks for the info.
I'll link Issue https://github.com/jcryptool/crypto/issues/230 to this one, so it's recognizable that this is being worked on.

Best regards, Thorben
