### ISSUE TITLE
Test algorithm perspective functionality

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#296]
Test Algorithm-Perspective

TODO: while testing the first ones, develop a scheme for evaluation like in #287. Try to find a good trade-off to the effect of maximum efficiency (we only want to see if there are any systemic problems).

These UI paths were deemed representative and should be tested. Post results as comments in this issue for now to be sorted out later.
| Getestet | Status| Verfahren | Kommentar |
| --- | --- | --- | --- |
| @grthor  | 🏁  | Asymmetric Block Ciphers \ ElGamal |  |
| @CharlotteMagister / @grthor  | 🏁   |  Asymmetric Block Ciphers \ RSA |  | 
| @grthor | 🏁  | Block Ciphers \ Twofish | Help icon with no function. Dropdown for keylength selection availabel but at no time changeable | 
| @grthor | ❌  | Hybrid Ciphers \ McEliecePointchevalCipher | Trying to encrypt the default text with a default McElieceCCA2 freezes JCT. No exception thrown. | 
| @grthor  | 🏁 | Message Authentication Codes \ CMac \ CmacDESede | | 
| @grthor | 🏁  | Message Authentication Codes \ HMac \ HmacRIPEMD320 | Outputs something, but may not be correct | 
| @Eduard951 | :checkered_flag: | Message Authentication Codes \ CBCMac \ CBCmacSerpent | When the user wants to specify a parameter and just adds " " (Spacebar) the field "finish" is green and the user can finish the configuration. The field expects a hexadecimal input, but when the user types for example the letter "G" two times in a row the Finish-Button can be clicked. | 
| @grthor | 🏁 | Message Authentication Codes \ TwoTrackMac \ TwoTrackMac160 | Outputs something, but may not be correct | 
| @Eduard951 | 🏁 | Message Digests \ SHA384 | | 
| @Eduard951 | ❌ | Password-Based Ciphers \ PbeWithSHAAnd3_KeyTripleDES_CBC | Nothing happens when you try to click [run button. log](https://github.com/jcryptool/crypto/files/5414352/log.TripleKey_error_20_10_2020.txt)
| @Eduard951 | 🏁 | Pseudo Random Number Generators \ SHA1PRNG | | 
| @Eduard951 | ❌ | Signatures \ MeRSA | You cant decrypt message, the [key dissapears. log](https://github.com/jcryptool/crypto/files/5414359/log.Mersa_20_10_2020.txt) | 
| @Eduard951 | 🏁  | Signatures \ RSASignaturePKCS1v15 \ RIPEMD160/RSA | | 
| @Eduard951 | 🏁 | Signatures \ IQGQSignature \ IQGQ | | 
| @Eduard951 | 🏁 | Signatures \ DSASignature \ RAW/DSA | | 
| @CharlotteMagister| 🏁 | Signatures \ CMSSSignature \ CMSSwithSHA512andWinternitzOTS_1 | | 
| @CharlotteMagister | ❌ | Signatures \ IQRDSASignature \ IQRDSA | Mac Problem: German and English version do not output that signature verified | 
| @CharlotteMagister | ❌ | Signatures \ GMSSSignature \ GMSSwithSHA512 | Mac Problem: German version does not output that signature verified | 
| @CharlotteMagister  | ❌ | Signatures \ SSL_MD5andSHA1withRSA | Exception initialising signature error| 
| @CharlotteMagister | ❌ | Signatures \ MerkleOTSSignature \ MerkleOTSwithSHA512 | Mac Problem: German version does not output that signature verified |

**Comment by simlei** [comment]
An idea of how a test check list could look like can be seen in https://github.com/jcryptool/crypto/issues/287

**Comment by CharlotteMagister** [comment]
Will start testing the first three items, after a plan for testing is established.

**Comment by grthor** [comment]
@CharlotteMagister and I have just developed a checklist according to which the algorithm plug-ins are tested.

The checklist contains the following 4 points:
- [ ] test if all plugins are completely translated.
- [ ] see if all GUI elements have a function.
- [ ] check the context help for gross errors (spelling mistakes, strange phrases)
- [ ] test whether input fields can cope with incorrect entries (e.g. enter letters in input fields for numbers)

Due to the small size of the algorithm GUIs (maximum one dialog box with 2 pages) the checklist is much smaller than for the normal plugins (https://github.com/jcryptool/crypto/issues/287). 

We decided against testing the validity of the results of the algorithms, because the algorithms are provided by the crypto-provider Bouncycastle and we trust that they are correct.

**Comment by grthor** [comment]
Some Algorithms do not open at all:
- ~Message Authentication Codes / CBCMac / CBCMacMisty1~ fixed with https://github.com/jcryptool/core/commit/d1bae299f7c25f91ecb809c4b5ae763b5bc83887
- ~Message Authentication Codes / CBCMac / SAFER~ fixed with https://github.com/jcryptool/core/commit/d1bae299f7c25f91ecb809c4b5ae763b5bc83887
- ~Message Authentication Codes / CBCMac / SAFER++~ fixed with https://github.com/jcryptool/core/commit/d1bae299f7c25f91ecb809c4b5ae763b5bc83887
- All entries in Message Authentication Codes / HMac
- All entries in Authentication Codes / TwoTrackMac

List to be continued

**Comment by CharlotteMagister** [comment]
I tested Asymmetric Block Ciphers \ RSA. I did not find any issues with it, but when clicking between the Asymmetric Block Ciphers and the Operations View the change in the text displayed in the Help box appears inconsistent. Sometimes the text vanishes and sometimes it appears again.

**Comment by Eduard951** [comment]
I tested Message Authentication Codes \ HMac \ CBCmacSerpent. I did find some issues. When the user wants to specify a parameter and just adds " " (Spacebar) the field "finish" is green and the user can finish the configuration. The field expects a hexadecimal input, but when the user types for example the letter "G" two times in a row the Finish-Button can be clicked.
I dont´t think this works as intended.

**Comment by Eduard951** [comment]
I tested:

Pseudo Random Number Generators \ SHA1PRNG
Message Digests \ SHA384

Both working as intended.

**Comment by Eduard951** [comment]
Tested Password-Based Ciphers \ PbeWithSHAAnd3_KeyTripleDES_CBC:

Nothing happens when you try to click run button.
[log(TripleKey_error_20_10_2020).txt](https://github.com/jcryptool/crypto/files/5414352/log.TripleKey_error_20_10_2020.txt)


Also tested Signatures \ MeRSA:

You cant decrypt message, the key dissapears.
[log(Mersa_20_10_2020).txt](https://github.com/jcryptool/crypto/files/5414359/log.Mersa_20_10_2020.txt)

**Comment by Eduard951** [comment]
Working:
Signatures \ IQGQSignature \ IQGQ
Signatures \ DSASignature \ RAW/DSA
Signatures \ RSASignaturePKCS1v15 \ RIPEMD160/RSA

**Comment by simlei** [comment]
Closed with the release of v1.0.0
