### ISSUE TITLE
Visual plugin: SSL / TLS handshake

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#308]
SSL / TLS Handshake (Protocol glitch & hangup)

- see original: https://github.com/jcryptool/crypto/issues/287#issuecomment-605443955

- **Prio Medium/high** erroneus behavior without feedback (I1)
- **Prio low/medium** textual (translation, help), context help integration
- Not sure: is it necessary to disable "information" buttons when proceeding to next step?
  Information could be nice to display without going to previous step! see I2)
- cipher suite random selections and proceeding as in I1) results in erroneous behavior after step 1 in client. Unacceptable without some kind of message; graphics glitches (arrows).

**Textual:**

- Online help:
    - Short introductory "Welcome to our online help for the SSL/TLS handshake plugin.". I'm not a fan of it, would remove it. It is however very short which could be acceptable. Should make general decision on this.
    - "Schritt-für-Schritt" is "word-by-word" translation --> "Schritt für Schritt"

**I1)**

![ssl_tls_hs1](https://user-images.githubusercontent.com/982379/77823404-39614680-70fb-11ea-8bfa-8936cd423544.gif)

**I2)**

![ssl_tls_hs2](https://user-images.githubusercontent.com/982379/77823402-36665600-70fb-11ea-8572-40f5bc4f8590.gif)

**I3)**

![ssl_tls_hs3](https://user-images.githubusercontent.com/982379/77823400-336b6580-70fb-11ea-927a-1a4effb719a9.png)

**Comment by grthor** [comment]
The incorrect behavior of the plugin when there is no shared cipher suite is intentional. But to make it clear that the client has to send a new "Client Hello" to the server to establish a connection I have added a pop-up dialog which explains exactly this (see screenshot).

![image](https://user-images.githubusercontent.com/20046726/80709335-6a171000-8aed-11ea-9920-3aca3078eec5.png)

This solution is not the pinnacle of usability design, but the logic of the plugin is based on checks whether a composite is visible or not. Therefore the ServerHelloComposite has to be made invisible to not disturb the program flow in the plugin. The alternative would be to change the plugin to use enums as indicators in which step the plugin is currently at. This would allow ServerHelloComposite to only be disabled instead of hidden. However, this solution would require a multiple of the effort of the pop-up solution. Therefore I decided to use the pop-up solution.

**Comment by simlei** [comment]
- Introduced better error handling for step transitions (dialog box), e.g. when the ServerHello step fails with bad cipher suite
- changed help a bit w.r.t. notes in comment 1
- Introduced live checking of user input and visual indicator in HelloServer step:

![image](https://user-images.githubusercontent.com/982379/80712862-dd6f5080-8af2-11ea-802e-40bcdf9e91cd.png)

![image](https://user-images.githubusercontent.com/982379/80713695-27a50180-8af4-11ea-895b-874c676ea98b.png)


which also explains to the user that missing options for TLS 1.0 and 1.1 can be due to the parameters in the HelloClient step. It prevents the user from giving up clicking the "next button" -- now they know what to expect when clicking it.

I'd consider this "good enough" for JCT v1.0 from this point of view.
