### ISSUE TITLE
Visual plugin: Zudo-Ku game

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#311]
Test & fix Zudo-Ku game as done with the other plug-ins in #287 

@tassadarius I think that you wanted this issue

**Comment by tassadarius** [comment]
# [Game] Zudo-ku

### UI

* [x] Resize artifacts  
* [x] Layout consistency

## English

### Online help (very detailed)
 * [x] has context help
 * [x] has online help
 * [x] has toolbar button that shows context help

### Plugin
* [x] Walk-through major functions
* [x] Walk-through, different order
* [x] Typos

## German

### Online help
* [x] has context help
* [x] has online help
* [x] has toolbar button that shows context help

### Plugin

* [x] walk-through major functions
* [x] walk-through, different order
* [x] Typos

### Textual Problems

`Online Help` [...] und aufgedeckt. **ü**berprüfe,

# Usability Test for this plugin

First thing is you consult the Online or Context help because you have no idea how the game works. That's not so a big deal, and after that it makes sense.

So you figure out how the challenge mechanic works - that's OK.
Then you have to figure out that the Cheat button actually is the additional game mode where the computer cheats in the Sudoku.
If you see the computer cheating, it is marked red.

Here now comes the major problem of the Plugin:
**You cannot really win (or lose)**

You can figure out which tile is wrong, but you can neither mark it or select it. You can reveal all cards and see if you were right, but there's no visual feedback.
I don't even know if it's the aim of the game to do that.

The Online help also does not really explain a lot - it says "figure it out yourself". That is for a learning software imho not a good approach. There should be at least a way to access a solution or an explanation that helps in the context of zero knowledge proofs and the application.

My suggestions:

 * Reorder the buttons and make a better description (e. g. "Cheat" does nothing when you click it. It should explain that the computer tries to cheat you)
* Check if you can make a "winning condition", e. g. like in Minesweeper where you mark the mine (cheating position) and then reveal to see if it's correct.
* Give an example in the Online help how zero knowledge proofs are used and why they are useful
