### ISSUE TITLE
CRT plugin action/toolbar buttons and fixes

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#326]
- [x] introduce a "restart" button and functionality
- [x] Export calculations button, enabled only if there is something to export.
- [x] "Latex" -> "LaTeX" | Fixed with https://github.com/jcryptool/crypto/commit/bd6bf95e289da9ba7e2361de0a9aeb25fe1b3024 by @grthor

**Comment by grthor** [comment]
Punkt 2. Die Buttons sollen aus dem Menu direkt in die Toolbar verschoben werden, da Nutzer das Menü nicht öffnen.

**Comment by grthor** [comment]
Point 2 fixed with https://github.com/jcryptool/crypto/commit/e6af458a28daeb2e6a462e376907f046ba5089dc.

I replaced the entries in the toolbar menu "Export to CSV", "Export to PDF" and "Export to TEX" with icons and moved then directly in the toolbar. The icons are directly visible to make it easier for a user to find the functions.

I created the icons for pdf, csv and tex because there were no good 16x16 available on the internet.

This is how it looks now:
![image](https://user-images.githubusercontent.com/20046726/89217708-e9c0e900-d5cc-11ea-9e9f-d4f40a3f7b7f.png)

The icons may be a bit small, but you can recognize them. When you hoover on the icons the tooltips "Export to CSV", "Export to PDF" and "Export to TEX" are shown.

I will close the issue, because all points are fixed.

**Comment by simlei** [comment]
perfect icons :)
